const initialGroups = [
    { id: 1,  name: 'CS-101: Intro to Computer Science CS-101: Intro to Computer Science CS-101: Intro to Computer Science' },
    { id: 2,  name: 'Math-202: Linear Algebra' },
    { id: 3,  name: 'Biology Buddies Club' },
    { id: 4,  name: 'Chem-404: Organic Chemistry Lab' },
    { id: 5,  name: 'Physics-505: Quantum Mechanics' },
    { id: 6,  name: 'Drama Society' },
    { id: 7,  name: 'History-707: Modern World History' },
    { id: 8,  name: 'Geo Explorers Club' },
    { id: 9,  name: 'CS-909: Data Structures' },
    { id: 10, name: 'Math-1010: Calculus I' },
    { id: 11, name: 'Astronomy Stargazers' },
    { id: 12, name: 'Robotics Team' },
    { id: 13, name: 'Philosophy Forum' },
    { id: 14, name: 'ENG-1414: Creative Writing' },
    { id: 15, name: 'Environmental Action Society' },
    { id: 16, name: 'GEO-1616: Climatology Seminar' },
    { id: 17, name: 'Cybersecurity Lab' },
    { id: 18, name: 'AI-1818: Machine Learning' },
    { id: 19, name: 'Business Case Competition' },
    { id: 20, name: 'Language Exchange Program' },
    { id: 21, name: 'CS-2121: Web Development' },
    { id: 22, name: 'Math-2222: Probability and Statistics' },
    { id: 23, name: 'Art Appreciation Club' },
    { id: 24, name: 'Music Band Society' },
    { id: 25, name: 'CS-2525: Software Engineering' },
    { id: 26, name: 'Math-2626: Differential Equations' },
    { id: 27, name: 'Chemistry Olympiad Prep' },
    { id: 28, name: 'Physics-2828: Thermodynamics' },
    { id: 29, name: 'CS-2929: Operating Systems' },
    { id: 30, name: 'Math-3030: Abstract Algebra' },
    { id: 31, name: 'Biology-3131: Genetics' },
    { id: 32, name: 'Chemistry-3232: Inorganic Chemistry' },
    { id: 33, name: 'Physics-3333: Electromagnetism' },
    { id: 34, name: 'CS-3434: Computer Networks' },
    { id: 35, name: 'Math-3535: Real Analysis' },
];

export default initialGroups;