const initialTasks = [
    {
        id: 1,
        title: 'Design login flow',
        description: 'Create wireframes and interactions for the new login flow.',
        createdAt: '2025-04-01',
        assignedAt: '2025-04-02',
        deadline: '2025-04-28',
        assignedTo: 'Alice Smith',
        status: 'Completed',
    },
    {
        id: 2,
        title: 'Set up CI/CD',
        description: 'Configure GitHub Actions for build, test, and deploy.',
        createdAt: '2025-03-20',
        assignedAt: '2025-03-22',
        deadline: '2025-05-01',
        assignedTo: 'Bob Johnson',
        status: 'In Progress',
    },
    {
        id: 3,
        title: 'Write API documentation',
        description: 'Document all endpoints and request/response schemas.',
        createdAt: '2025-04-05',
        assignedAt: '2025-04-07',
        deadline: '2025-05-08',
        assignedTo: 'Carla Reyes',
        status: 'To Do',
    },
    {
        id: 4,
        title: 'Implement task dashboard',
        description: 'Build UI components for displaying tasks in columns.',
        createdAt: '2025-04-10',
        assignedAt: '2025-04-11',
        deadline: '2025-05-12',
        assignedTo: 'David Lee',
        status: 'In Progress',
    },
    {
        id: 5,
        title: 'User profile page',
        description: 'Create user settings and profile viewing page.',
        createdAt: '2025-04-12',
        assignedAt: '2025-04-13',
        deadline: '2025-05-15',
        assignedTo: 'Eva Müller',
        status: 'To Do',
    },
    {
        id: 6,
        title: 'Optimize database queries',
        description: 'Analyze and optimize slow SQL queries in reporting module.',
        createdAt: '2025-04-20',
        assignedAt: '2025-04-21',
        deadline: '2025-05-20',
        assignedTo: 'Frank Zhang',
        status: 'To Do',
    },
    {
        id: 7,
        title: 'Implement notifications',
        description: 'Add real-time notifications for task assignments and deadlines.',
        createdAt: '2025-04-22',
        assignedAt: '2025-04-23',
        deadline: '2025-05-25',
        assignedTo: 'Grace Kim',
        status: 'In Progress',
    },
    {
        id: 8,
        title: 'Set up performance monitoring',
        description: 'Integrate an APM tool and configure dashboards.',
        createdAt: '2025-04-25',
        assignedAt: '2025-04-26',
        deadline: '2025-06-01',
        assignedTo: 'Hiro Tanaka',
        status: 'To Do',
    },
    {
        id: 9,
        title: 'Final UI polish',
        description: 'Apply final design tweaks across all pages before release.',
        createdAt: '2025-04-28',
        assignedAt: '2025-05-01',
        deadline: '2025-05-18',
        assignedTo: 'Isabel García',
        status: 'To Do',
    },
    {
        id: 10,
        title: 'Conduct user testing',
        description: 'Gather feedback from users on the new features.',
        createdAt: '2025-05-01',
        assignedAt: '2025-05-02',
        deadline: '2025-05-30',
        assignedTo: 'Jack Brown',
        status: 'To Do',
    },
    {
        id: 11,
        title: 'Deploy to production',
        description: 'Release the new version to all users.',
        createdAt: '2025-05-05',
        assignedAt: '2025-05-06',
        deadline: '2025-06-05',
        assignedTo: 'Kathy White',
        status: 'To Do',
    },
    {
        id: 12,
        title: 'Post-release monitoring',
        description: 'Monitor system performance and user feedback after release.',
        createdAt: '2025-05-10',
        assignedAt: '2025-05-11',
        deadline: '2025-06-10',
        assignedTo: 'Liam Patel',
        status: 'To Do',
    },
];

export default initialTasks;